server:
  port: 8080

grpc:
  server:
    port: 59091

spring:
  application:
    name: collector
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      discovery:
        enabled: false
      uri: http://localhost:8888
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "telemetry.collector"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.telemetry.serialization.AvroSerializer
        "acks": all
        "retries": 3
        "batch.size": 16384
        "linger.ms": 1
        "buffer.memory": 33554432
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/