spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    snapshots-consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: analyzer-snapshots-group
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.telemetry.serialization.SensorsSnapshotDeserializer
        enable.auto.commit: false
        auto.offset.reset: earliest
      topic: telemetry.snapshots.v1
    hubs-consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: analyzer-hubs-group
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.telemetry.serialization.HubEventDeserializer
        enable.auto.commit: false
        auto.offset.reset: earliest
      topic: telemetry.hubs.v1